#!/bin/sh
#
# LightDM wrapper to run around X sessions.

echo "Running X session wrapper"

# Load profile
for file in "/etc/profile" "$HOME/.profile" "/etc/xprofile" "$HOME/.xprofile"; do
    if [ -f "$file" ]; then
        echo "Loading profile from $file";
        . "$file"
    fi
done

# Load resources
for file in "/etc/X11/Xresources" "$HOME/.Xresources"; do
    if [ -f "$file" ]; then
        echo "Loading resource: $file"
        xrdb -nocpp -merge "$file"
    fi
done

# Load keymaps
for file in "/etc/X11/Xkbmap" "$HOME/.Xkbmap"; do
    if [ -f "$file" ]; then
        echo "Loading keymap: $file"
        setxkbmap `cat "$file"`
        XKB_IN_USE=yes
    fi
done

# Load xmodmap if not using XKB
if [ -z "$XKB_IN_USE" ]; then
    for file in "/etc/X11/Xmodmap" "$HOME/.Xmodmap"; do
        if [ -f "$file" ]; then
           echo "Loading modmap: $file"
           xmodmap "$file"
        fi
    done
fi

unset XKB_IN_USE

# Run all system xinitrc shell scripts.
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

# Make sure dbus is available then set gsettings
export DISPLAY=:0

set_gsettings() {

if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
	# No DBUS session running, start one.
	eval `dbus-launch --sh-syntax`
fi

# Change keyboard layaout
_current_val="$(gsettings get org.gnome.desktop.input-sources sources)"
echo "${_current_val}" > /tmp/.input-sources
if [[ *'[]'* = "${_current_val}" ]]; then
	gsettings set org.gnome.desktop.input-sources sources "[('xkb','us')]"
fi


	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
	touch ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml


	# Set background
	xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path -n -t string -s "/usr/share/antergos/wallpapers/antergos-wallpaper.png"
	CMD=`grep image-path ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep image-path ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	done

	# Set theme
	CMD=`grep image-path ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep image-path ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml`
	done
	xfconf-query -c xsettings -p /Net/ThemeName -n -t string -s "Numix-Frost"

	CMD=`grep ThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep ThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	done
	xfconf-query -c xfwm4 -p /general/theme -n -t string -s "Numix-Frost-Light"

	# Set icon theme
	CMD=`grep theme ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep theme ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	xfconf-query -c xsettings -p /Net/IconThemeName -n -t string -s "Numix-Square"

	# Set compositor
	CMD=`grep IconThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep IconThemeName ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml`
	done
	xfconf-query -c xfwm4 -p /general/show_frame_shadow -n -t bool -s "true"

	# Set workspaces count
	CMD=`grep show_frame_shadow ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep show_frame_shadow ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	xfconf-query -c xfwm4 -p /general/workspace_count -n -t int -s 2

	# Set panels
	CMD=`grep workspace_count ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep workspace_count ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml`
	done
	xfconf-query -c xfce4-panel -p /panels/panel-2/autohide -n -t bool -s "true"

	CMD=`grep autohide ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep autohide ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	done
	xfconf-query -c xfce4-panel -p /panels/panel-1/size -n -t int -s 25

	# Set menu logo
	CMD=`grep size ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	while [ "${CMD}" == "" ]; do
		sleep 3
		CMD=`grep size ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml`
	done
xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-icon -n -t string -s "/usr/share/antergos/antergos-menu-logo-dark-bg.png"


}

echo "Running set-gsettings..."
set_gsettings > /tmp/.set_gsettings 2>&1;
echo "set-gsettings complete"
gnome-keyring-daemon -rd
echo "X session wrapper complete, running session $@"

exec $@
