#!/bin/sh
#
# LightDM wrapper to run around X sessions.

echo "Running X session wrapper"

# Load profile
for file in "/etc/profile" "$HOME/.profile" "/etc/xprofile" "$HOME/.xprofile"; do
    if [ -f "$file" ]; then
        echo "Loading profile from $file";
        . "$file"
    fi
done

# Load resources
for file in "/etc/X11/Xresources" "$HOME/.Xresources"; do
    if [ -f "$file" ]; then
        echo "Loading resource: $file"
        xrdb -nocpp -merge "$file"
    fi
done

# Load keymaps
for file in "/etc/X11/Xkbmap" "$HOME/.Xkbmap"; do
    if [ -f "$file" ]; then
        echo "Loading keymap: $file"
        setxkbmap `cat "$file"`
        XKB_IN_USE=yes
    fi
done

# Load xmodmap if not using XKB
if [ -z "$XKB_IN_USE" ]; then
    for file in "/etc/X11/Xmodmap" "$HOME/.Xmodmap"; do
        if [ -f "$file" ]; then
           echo "Loading modmap: $file"
           xmodmap "$file"
        fi
    done
fi

unset XKB_IN_USE

# Run all system xinitrc shell scripts.
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

# Make sure dbus is available then set gsettings
export DISPLAY=:0

set_gsettings() {

if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
	# No DBUS session running, start one.
	eval `dbus-launch --sh-syntax`
fi

	# Set KDE in .dmrc
	echo "[Desktop]" > ${CN_DESTDIR}/home/${CN_USER_NAME}/.dmrc
	echo "Session=kde-plasma" >> ${CN_DESTDIR}/home/${CN_USER_NAME}/.dmrc
	chroot ${CN_DESTDIR} chown ${CN_USER_NAME}:users /home/${CN_USER_NAME}/.dmrc

	# Force QtCurve to use our theme
	rm -R ${CN_DESTDIR}/usr/share/kstyle/themes/qtcurve.themerc

	# Setup user defaults
	chroot ${CN_DESTDIR} /usr/share/antergos-kde-setup/install.sh ${CN_USER_NAME}

	# Setup root defaults
	cp -R ${CN_DESTDIR}/etc/skel/.config ${CN_DESTDIR}/root
	cp ${CN_DESTDIR}/etc/skel/.gtkrc-2.0-kde4 ${CN_DESTDIR}/root
	chroot ${CN_DESTDIR} "ln -s /root/.gtkrc-2.0-kde4 /root/.gtkrc-2.0"

	# When applications transition to Qt5 they will look for config files in the standardized (XDG) locations. Create
	# symlinks during the transitional period until all apps are updated to use the new config file paths.
	link_config() {

		if [[ ${1} != "apps:" ]] && [[ ${1} != "" ]]; then
			app=${1:6}
			app_old="/home/${CN_USER_NAME}/.kde4/share/apps/${app}"
			app_new="/home/${CN_USER_NAME}/.local/share/${app}"
			chroot ${CN_DESTDIR} "ln -s ${app_old}${app_new}" ${CN_USER_NAME}
		fi
		if [[ ${2} != "conf:" ]] && [[ ${2} != "" ]]; then
			conf=${2:6}
			conf_old="/home/${CN_USER_NAME}/.kde4/share/config/${conf}"
			conf_new="/home/${CN_USER_NAME}/.config/${conf}"
			chroot ${CN_DESTDIR} "ln -s ${conf_old}${conf_new}" ${CN_USER_NAME}
		fi

	}

	#for i in konsole; do
	#	link_config apps:${i};
	#done
	#for i in kdeglobals; do
	#	link_config apps: conf:kdeglobals;
	#done

	## Set default directories
chroot ${CN_DESTDIR} su -c xdg-user-dirs-update ${CN_USER_NAME}

}

echo "Running set-gsettings..."
set_gsettings > /tmp/.set_gsettings 2>&1;
echo "set-gsettings complete"
gnome-keyring-daemon -rd
echo "X session wrapper complete, running session $@"

exec $@
